### ISSUE TITLE
README directions about labels csv unclear

### ISSUE THREAD

**Issue by same-code-different-day** [akhvorov/TraceSim#1]
Hi Aleksandr, I've been reading through your paper and project here and find it very interesting. I've tried setting up the project locally and am running into issues with the labels csv. The readme suggests it has the headers 'rid1, rid2, label' but I'm not clear on what data I may need to add to that file manually. The code seems to read in label as an int, but I was hoping you could give an example of what needs to be added here.

If you think adding an example csv and directory of fake call stacks to the project would help demonstate, I would love to contribute.

Thanks!

**Comment by akhvorov** [comment]
Hi Peter,

Thanks for your interest in our project!
Label has int type and can be one of 0 and 1. Label means that two reports
are similar or not. It can be readed as int(rid1 is similar to rid2).

I will add some examples in the near future. Thank you for your suggestion!

вс, 11 июл. 2021 г. в 22:18, Peter Strunk ***@***.***>:

**Comment by same-code-different-day** [comment]
That makes sense. So using the example trace ("id": 223576912) in the README, it'd be something like:

rid1,rid2,label
223576912,223576913,0   (because diffferent)
223576912,223576912,1   (because self is same)
223576912,223576914,1   (because similar enough)

and it seems to expect the id is also the filename so the dir of trace files should contain 223576912.json, 223576913.json, and 223576914.json for the above example?

**Comment by akhvorov** [comment]
Yes, your example is correct, and you are right that reports with such ids are expected to have these names.

Update Readme according to your comments.
